app:
  name: ${APP_NAME:"Ayaka Backend"}
  version: ${APP_VERSION:"v1.0.0"}
  env: ${APP_ENV:"development"}

server:
  port: ${HTTP_PORT:8000}

log:
  file_path: "logs/app.log"
  max_size: 10
  max_backups: 5
  max_age: 30
  compress: true

database:
  host: ${DATABASE_HOST:localhost}
  port: ${DATABASE_PORT:5432}
  user: ${DATABASE_USER:postgres}
  pass: ${DATABASE_PASS:""}
  name: ${DATABASE_NAME:ayaka_db}

jwt:
  secret: ${JWT_ACCESS_SECRET:"secret_default"}
  expired: ${JWT_ACCESS_EXPIRED:24}
  refresh_secret: ${JWT_REFRESH_SECRET:"refresh_secret_default"}
  refresh_expired: ${JWT_REFRESH_EXPIRED:1440}

frontend:
  url: ${FRONTEND_URL:"http://localhost:3000"}

email:
  host: ${SMTP_HOST:"smtp.gmail.com"}
  port: ${SMTP_PORT:"587"}
  user: ${SMTP_USER:""}
  pass: ${SMTP_PASS:""}