name: Furina Backend CI

on:
  push:
    branches: [ main, master, dev, "feature/prodept-poc" ]
  pull_request:
    branches: [ main, master, dev ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Setup environment Go compiler
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25' # Match to your Go version
          cache: true

      # 3. Download dependencies
      - name: Install Dependencies
        run: go mod download

      # 4. Run Unit Test
      - name: Run Unit Tests
        env:
          DATABASE_HOST: localhost
          DATABASE_PORT: 5432
          DATABASE_USER: postgres
          DATABASE_PASS: password
          DATABASE_NAME: ayaka_db
          SERVER_PORT: 8000
          SMTP_USER: dummy_user
          SMTP_PASS: dummy_password
        run: go test -v -coverprofile=coverage.txt ./...
      
      # 5. Build Application
      - name: Build Furina
        run: go build -o furina-app main.go svc

      # 6. Upload
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: furina-binary
          path: furina-app